### ISSUE TITLE
Constant Distribution

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaStats/Distributions.jl#1098]
I'm working on something that involves both stochastic and deterministic functions and it would be nice to have a `Constant <: Distribution` that satisfies the Distributions API but always returns its parameter.  Would that be something welcome in Distributions.jl?

**Comment by johnczito** [comment]
This has come up before (#1040), and there's a PR outstanding (#861). Depending on your needs, you can get this behavior by creating a `Normal` with zero variance, or a `DiscreteNonParametric` with one support point.

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaStats/Distributions.jl/pull/1231.

**Comment by oschulz** [comment]
I have a `ConstValueDist` in ValueShapes.jl that is very similar to the new `Dirac`, but it can also handle non-univariate values. Wouldn't mind to get rid of it in favor of `Dirac` though - would it be acceptable to add a type parameter for the variate form to `Dirac`? If so, I could put a PR together.

**Comment by devmotion** [comment]
Sure, it's indeed a bit limiting that it only works with real numbers currently.

**Comment by oschulz** [comment]
Ok, I'll see if I can port that over from https://github.com/oschulz/ValueShapes.jl/blob/master/src/const_value_dist.jl .

I'll have to see how I handle `NamedTupleVariate`s though, since that's a ValueShape-specific thing so far (it supports dists with actual named `NamedTuples` as variates and can reshape them to flat `Multivariate` dists an vice-versa). Having `Distributions.Dirac(x::NamedTuple{names}) = ...` in ValueShapes would be type-piracy, obviously.

In principle, could there be room in Distributions.jl for declaring a variate type for `NamedTuple`s (and maybe for structs as well), next to `ArrayLikeVariate` (#1313)?

**Comment by devmotion** [comment]
I think a possible approach would be to define functions `variateform(::Real) = ArrayLikeVariate{0}` and `variateform(::Array{<:Real,N}) where {N} = ArrayLikeVariate{N}` in Distributions, and then just use `variateform` in the constructor of `Dirac`. Then packages such as ValueShapes.jl could define their own variate types and could use `Dirac` if they just implement `variateform` for the types that their variate form covers.

**Comment by oschulz** [comment]
Oh, yes, having a generic function `variateform` in Distributions would be very nice. But I guess for `Base` types like `NamedTuple` we'd still need to define the respective method and variate type in Distributions, right? If ValueShapes would define `variateform(::NamedTuple{names})` it would still be type piracy. I would like to move part of ValueShapes support for non-array-like variates to `Distributions` though, if they would be judged acceptable.
