### ISSUE TITLE
Possibly overflow?

### ISSUE THREAD

**Issue by Jovansam** [JuliaStats/Distributions.jl#1135]
There is a small problem: the first gives an incorrect figure.
```julia
using Distributions, Plots
display(plot((0.6:0.020519755018019205:1.5),pdf.(LogNormal(0,(0.026^2)),(0.6:0.020519755018019205:1.5))))
display(plot((0.6:0.02:1.5),pdf.(LogNormal(0,(0.026^2)),(0.6:0.02:1.5))))
```
Based on Matlab, I know it should be look more like the second or third.
I need to use the first since "0.020519755018019205" is recovered from another computation.

**Comment by andreasnoack** [comment]
If Matlab gives a plot like the second one for the first range, then it's a bug in Matlab. All the mass is concentrated around `1.0` but you don't evaluate the `pdf` at 1.0 with the chosen step size
```julia
julia> _x1 = 0.6:0.020519755018019205:1.5
0.6:0.020519755018019205:1.4823494657748257

julia> _x1[20], _x1[21]
(0.9898753453423649, 1.010395100360384)

julia> range(_x1[20], stop=_x1[21], length=1000) |> t -> plot(t, pdf.(LogNormal(0.0, 0.026^2), t))
```
<img width="619" alt="Screen Shot 2020-06-15 at 11 19 52" src="https://user-images.githubusercontent.com/505001/84640602-3277f200-aefa-11ea-8ea7-7104fd34f53f.png">

However, I don't think there is a bug in Matlab. I'd guess that you shouldn't square the second argument since the `LogNormal` is parameterized with the standard deviation and
```julia
julia> plot(_x1, pdf.(LogNormal(0.0, 0.026), _x1))
```
gives
<img width="618" alt="Screen Shot 2020-06-15 at 11 26 28" src="https://user-images.githubusercontent.com/505001/84641309-23de0a80-aefb-11ea-9548-187be5c8911d.png">

discourse.julialang.org is better suited for questions like these.

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
