### ISSUE TITLE
qqbuild automatically throws out min and max values

### ISSUE THREAD

**Issue by HiramTheHero** [JuliaStats/Distributions.jl#1378]
I originally posted this issue on StatsPlots.jl, and they referred me to post the issue here.

Here is the link explaining the issue: [https://github.com/JuliaPlots/StatsPlots.jl/issues/461#issue-956142608](https://github.com/JuliaPlots/StatsPlots.jl/issues/461#issue-956142608)

Here is the comment that explains why the issue should be posted here: [https://github.com/JuliaPlots/StatsPlots.jl/issues/461#issuecomment-891113224](https://github.com/JuliaPlots/StatsPlots.jl/issues/461#issuecomment-891113224)

**Comment by JoshuaWhittemore** [comment]
Thank you @HiramTheHero for filing this.  I noticed it too.  I think the issue name should be changed to `qqbuild automatically throws out min and max values`, or something like that.  @sethaxen 's nice example shows the issue:
```julia
julia> using Distributions

julia> qqpair = Distributions.qqbuild(Normal(), [1,2,3])
QQPair{Array{Float64,1},Array{Float64,1}}([0.0], [2.0])

julia>
```

**Comment by scheidan** [comment]
The problem is how `qqbuild` selects the grid points:
https://github.com/JuliaStats/Distributions.jl/blob/35125579a77b938f8d4a8bd2be23cbf1f2ddf225/src/qq.jl#L16
which is shorter than `length(x)`.

This solution would lead to the same behavior as R (ensuring that `length(n) == length(qx) == length(qd)`):
```Julia
"""
Generates the sequence of probability points

Reference for the selection of  `a`:
Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
Language_.  Wadsworth & Brooks/Cole. 
"""
function ppoints(x)
    n = length(x)
    a =  n <= 10 ? 3/8 : 0.5
    start = (1-a)/(n + 1 - 2*a)
    stop = (n-a)/(n + 1 - 2*a)
    range(start, stop, length=n)
end
```

```Julia
function qqbuild(x::AbstractVector, d::UnivariateDistribution)
    grid = ppoints(x)
    qx = quantile(x, grid)
    qd = quantile.(Ref(d), grid)
    return QQPair(qx, qd)
end
```

This is a breaking change but I think the current behavior is _extremely dangerous_ for the intended use to build qqplots as it hides potential outliers.

If we agree that this is an improvement, I'd be happy to put a little PR together
