### ISSUE TITLE
Allow Reflections by Removing Positivity Constraint for `LocationScale`

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaStats/Distributions.jl#1441]
Many asymmetric distributions are more easily expressed with a location-scale transformation that has a negative scale parameter. For instance, the lower tail of a variable can be modeled as a Generalized Pareto distribution with a negative scale. I propose removing the positivity constraint on `LocationScale.σ` to allow this.

**Comment by devmotion** [comment]
A quick summary of my comments on Slack: I don't think `LocationScale` should support it since it would not be a proper scale anymore and not correspond to the common definitions of location-scale families. I'm not opposed to a differently named type (and possibly deprecating `LocationScale`) that supports reflections.
