### ISSUE TITLE
Warnings in latest release?

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distributions.jl#1479]
I am getting a bunch of warnings like this with a recent update:

WARNING: Method definition (::Type{Distributions.InverseGaussian{T} where T<:Real})(T<:Real, T<:Real) where {T<:Real} in module Distributions at /home/juliohm/.julia/packages/Distributions/AqbOM/src/univariate/continuous/inversegaussian.jl:31 overwritten at /home/juliohm/.julia/packages/Distributions/AqbOM/src/univariate/continuous/inversegaussian.jl:27.
  ** incremental compilation may be fatally broken for this module

**Comment by devmotion** [comment]
Ah that's unfortunate. I checked the logs of https://github.com/JuliaStats/Distributions.jl/runs/4804830478?check_suite_focus=true before merging  https://github.com/JuliaStats/Distributions.jl/pull/1472 but no warnings show up there. However, it seems test with Julia 1.0 show warnings for `InverseGaussian` and `Levy`: https://github.com/JuliaStats/Distributions.jl/runs/4804830399?check_suite_focus=true#step:6:43

Which Julia version did you use? And did you see any other warnings since you wrote "a bunch of warnings"?

In any case the fix should be easy. Similar to other distributions (not changed by this PR) we can just add an inner constructor.

**Comment by devmotion** [comment]
In fact, the PR and these warnings uncovered a bug:
```julia
julia> using Distributions

julia> InverseGaussian(0.0, 0.0)
InverseGaussian{Float64}(μ=0.0, λ=0.0)

julia> InverseGaussian(0.0, 0.0; check_args=true)
ERROR: ArgumentError: InverseGaussian: the condition μ > zero(μ) && λ > zero(λ) is not satisfied.
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/Distributions/381c4/src/utils.jl:6 [inlined]
 [2] #InverseGaussian#152
   @ ~/.julia/packages/Distributions/381c4/src/univariate/continuous/inversegaussian.jl:32 [inlined]
 [3] top-level scope
   @ REPL[5]:1
```
The first call should dispatch to `InverseGaussian(0.0, 0.0; check_args=true)` but is actually a call of the inner constructor because the outer constructor was defined as `InverseGaussian(::T, ::T; check_args=true) where T` instead of `InverseGaussian(::T, ::T; check_args=true) where {T<:Real}`.

**Comment by juliohm** [comment]
I am on Julia v1.6 and the warnings are for Levy and InverseGaussian, but they are repeated multiple times.

**Comment by devmotion** [comment]
Not completely sure but I assume they are repeated if Distributions is loaded multiple times by different packages.
