### ISSUE TITLE
Convert does not respect type of Normal

### ISSUE THREAD

**Issue by sethaxen** [JuliaStats/Distributions.jl#1485]
#1472 made some changes to the constructors of `Normal`, so that now we get the following:

```julia
julia> d = Normal{Int64}(0, 1)
Normal{Int64}(μ=0, σ=1)

julia> convert(Normal{Int}, d)
Normal{Float64}(μ=0.0, σ=1.0)

julia> truncated(d, 0, 1)
ERROR: TypeError: in new, expected Normal{Int64}, got a value of type Normal{Float64}
Stacktrace:
 [1] Truncated
   @ ~/projects/Distributions.jl/src/truncate.jl:57 [inlined]
 [2] truncated(d::Normal{Int64}, l::Int64, u::Int64)
   @ Distributions ~/projects/Distributions.jl/src/truncate.jl:39
 [3] top-level scope
   @ REPL[36]:1
```

The latter happens I guess because the constructor for `Truncated` implicitly calls `convert(Normal{Int}, d)` and throws an error when it gets the wrong type.

**Comment by sethaxen** [comment]
Same happens now for `Uniform`:
```julia
julia> convert(Uniform{Int}, Uniform{Int}(0, 1))
Uniform{Float64}(a=0.0, b=1.0)
```

**Comment by devmotion** [comment]
#1472 did not change `convert`, it seems previously it just worked by accident since it did not actually call the constructor for integers in e.g. the case of `Normal` which - for historic reasons that I think should be changed - always promotes integers to floating point numbers.

So possible solutions would be to e.g. use more standard definitions of `convert` that use the inner constructors directly, without relying or falling back on any promotions of the outer constructors, or to remove any such promotions from integers to floating point numbers in the constructors. In my opinion, both things should be done - but since not promoting integers might require changes in other methods it is probably easier to start with using the inner constructors in `convert`.

**Comment by devmotion** [comment]
In some sense it was even worse before #1472 since e.g. both `convert` definitions for `Normal` were inconsistent (example with Distributions 0.25.38):
```julia
julia> convert(Normal{Int}, 0, 1)
Normal{Float64}(μ=0.0, σ=1.0)

julia> convert(Normal{Int}, Normal{Int}(0, 1))
Normal{Int64}(μ=0, σ=1)
```

**Comment by devmotion** [comment]
Maybe we also have to move the `check_args` argument to the inner constructor, otherwise we can't rely on the implemented checks when we want to define something like `Base.convert(::Type{Normal{T}}, m::Real, s::Real) = Normal{T}(T(m), T(s))`.
