### ISSUE TITLE
Sampling from truncated mixture model results in an error

### ISSUE THREAD

**Issue by shamazmazum** [JuliaStats/Distributions.jl#1501]
Hi! I have Julia 1.7.3 and Distributions 0.25.45. The error is as follows:

~~~~
julia> dist = Truncated(MixtureModel(Normal, [(1.0, 0.0)]), 0, Inf);

julia> rand(dist, 10)
ERROR: AssertionError: cl <= p <= cr
Stacktrace:
  [1] quantile_bisect(d::MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, p::Float64, lx::Float64, rx::Float64, tol::Float64)
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/quantilealgs.jl:13
  [2] quantile_bisect(d::MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, p::Float64, lx::Float64, rx::Float64)
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/quantilealgs.jl:11
  [3] quantile(d::MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, p::Float64)
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/mixtures/mixturemodel.jl:447
  [4] quantile
    @ ~/.julia/packages/Distributions/9Albf/src/truncate.jl:128 [inlined]
  [5] rand
    @ ~/.julia/packages/Distributions/9Albf/src/univariates.jl:157 [inlined]
  [6] _rand!(rng::Random._GLOBAL_RNG, sampler::Truncated{MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, Continuous, Float64}, A::Vector{Float64})
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/univariates.jl:147
  [7] rand!
    @ ~/.julia/packages/Distributions/9Albf/src/univariates.jl:142 [inlined]
  [8] rand
    @ ~/.julia/packages/Distributions/9Albf/src/genericrand.jl:52 [inlined]
  [9] rand
    @ ~/.julia/packages/Distributions/9Albf/src/genericrand.jl:24 [inlined]
 [10] rand(s::Truncated{MixtureModel{Univariate, Continuous, Normal, Categorical{Float64, Vector{Float64}}}, Continuous, Float64}, dims::Int64)
    @ Distributions ~/.julia/packages/Distributions/9Albf/src/genericrand.jl:22
 [11] top-level scope
    @ REPL[21]:1
~~~~

**Comment by devmotion** [comment]
Two comments:
- `Truncated` is deprecated, it is recommended to use `truncated` instead. `truncated` may return optimized implementations (e.g., for `Uniform`) whereas `Truncated` always returns a fallback distribution of type `Truncated`.
- It is a quite special pathological example here: By default, and also for `Truncated`, inversion sampling is performed, i.e., samples are generated as `quantile(dist, rand())`. For mixture models `quantile` uses a bisection algorithm. The initial bracket is formed by the extrema of `quantile(ci, p)` of the components ci of the mixture model with non-zero probability: https://github.com/JuliaStats/Distributions.jl/blob/620a73acb4992fee8998b562837268defb4bae9c/src/mixtures/mixturemodel.jl#L446 In your example, the extrema are identical (there's only a single component) AND they are `1.0` for every quantile level (since the normal distribution is degenerate). However, `cdf(Normal(1, 0), 1.0) == 1.0` and hence the assertion in https://github.com/JuliaStats/Distributions.jl/blob/620a73acb4992fee8998b562837268defb4bae9c/src/quantilealgs.jl#L13 fails if the quantile level `p` is less than 1.

The simplest fix might be to add a check for `lx == rx` in https://github.com/JuliaStats/Distributions.jl/blob/620a73acb4992fee8998b562837268defb4bae9c/src/quantilealgs.jl#L3, and in this case return a type stable result directly.

**Comment by sethaxen** [comment]
Would it be worth it for a mixture model with a single component to just fall back to `quantile` called on that component? I guess there's the potential risk of type-instability that way.

**Comment by devmotion** [comment]
An additional advantage of handling it in the bisection algorithm would be that e.g. `median` (https://github.com/JuliaStats/Distributions.jl/blob/620a73acb4992fee8998b562837268defb4bae9c/src/mixtures/mixturemodel.jl#L452) would be fixed automatically.

**Comment by shamazmazum** [comment]
Thanks!
