### ISSUE TITLE
Type instability whenever calling randexp

### ISSUE THREAD

**Issue by enweg** [JuliaStats/Distributions.jl#1527]
https://github.com/JuliaStats/Distributions.jl/blob/eff3f1c456f53ce1e01cd69ac09b378a8da57248/src/univariate/continuous/exponential.jl#L104

I have noticed that even when declaring Gamma, Exponential and similar distributions to be of type Float32, sampling always returns a Float64. Not sure if this is intentional or not, but it seems to be easily fixed by always calling `randexp(rng, T)` with T being the type of the parameters of the distribution. 

Would be interested to know if this was intentional? It does not seem like it to me given that `rand` will return Float32 for gaussians of type Float32.

**Comment by devmotion** [comment]
Yes, this is intentional (BTW usually type instability refers to functions for which the type can't be inferred which is not the case here). There are some open issues (https://github.com/JuliaStats/Distributions.jl/issues/1071) and a PR that would fix current inconsistencies (https://github.com/JuliaStats/Distributions.jl/pull/1433). Unfortunately, there are some issues with dual numbers and I didn't have much time lately, but I hope I (or someone else) can pick it up and fix the remaining issues in the near future.
