### ISSUE TITLE
Random sample from truncated Beta is not correct

### ISSUE THREAD

**Issue by lf28** [JuliaStats/Distributions.jl#1548]
For truncated Beta distribution with parameters e.g. alpha = 10, beta =100, and truncate lower limit set at 0.5, all random samples are 1.0. One should however expect most samples are close to 0.5. 

`rand(truncated(Beta(10,100), lower= 0.5), 1000);
StatsPlots.plot(truncated(Beta(10,100), lower= 0.5))
`

The problem probably originates from beta_inc function though.

**Comment by devmotion** [comment]
It seems the problem here is not in StatsFuns or SpecialFuncions but that the branch in `rand` that is hit here operates with the CDF but not the log CDF: https://github.com/JuliaStats/Distributions.jl/blob/dd6ae8f4eac304f404b0069540a6c3bb1c667f92/src/truncate.jl#L196

In the example `truncated(Beta(10, 100); lower=0.5)`, we have
```julia
julia> logcdf(Beta(10,100), 0.5)
-7.203401329871172e-21

julia> cdf(Beta(10,100), 0.5)
1.0

julia> exp(logcdf(Beta(10,100), 0.5))
1.0
```
Hence `quantile(Beta(10, 100), lowercdf + mass * rand())` will always just call `quantile(Beta(10, 100), 1.0)`. This branch is hit since
```julia
julia> exp(logdiffcdf(Beta(10,100), 1.0, 0.5)) # stored as d.tp in the truncated distribution
7.203401329871193e-21
```
is less than 0.25.

**Comment by lf28** [comment]
Thanks for the quick and detailed reply. It makes sense. 

It seems there is no easy fix that works for all univariate distributions. I suppose the other branch, i.e. rejection sampling, will be very inefficient for situations like this but at least produce good samples.

**Comment by devmotion** [comment]
> I suppose the other branch, i.e. rejection sampling, will be very inefficient for situations like this but at least produce good samples.

I think very inefficient is almost an understatement here: The probability that you sample values in the desired range if you sample from the untruncated Beta distribution is around ~ 7.2e-21, so it will just not terminate in reasonable amount of time on average.

Performing the calculations in log-space seems to fix the issue though:
```julia
julia> using Distributions, StatsFuns, Random

julia> function rand_logspace(rng::Random.AbstractRNG, d::Truncated{<:ContinuousUnivariateDistribution})
           d0 = d.untruncated
           loglcdf = logcdf(d0, d.lower)
           x = logaddexp(loglcdf, d.logtp - randexp(rng))
           return invlogcdf(d0, x)
       end
rand_logspace (generic function with 1 method)

julia> rand_logspace(d::Truncated{<:ContinuousUnivariateDistribution}) = rand_logspace(Random.default_rng(), d)
rand_logspace (generic function with 2 methods)

julia> d = truncated(Beta(10, 100); lower=0.5);

julia> x = [rand_logspace(d) for _ in 1:100_000];

julia> mean(x)
0.5054318810132329

julia> extrema(x)
(0.5000001443587312, 0.5611275358796852)
```

Probably we should store `logcdf(d.untruncated, d.lower)` in `Truncated` as well, and then use the log-space computations if `d.tp` is below some threshold (since it will be slower than the non-log-space computations I assume).

**Comment by lf28** [comment]
Your approach is definitely better than the remedy I have done locally. I have resorted to slice sampling instead whenever d.lcdf is 1.0 (or tp is below some threshold). Slice sampler is very straightfoward for a truncated and unimodal distribution like this one but the samples are not iid. 

It seems the symmetric case works well to my surprise. i.e. 

`rand(truncated(Beta(100, 10); upper=0.5))`

that's why I chose to test lcdf instead of tp.

**Comment by lf28** [comment]
I am a little bit confused how invlogcdf avoids the floating number problem. It seems it is just a wrapper of quantile method with exp(lp) after all:

```
invlogcdf(d::UnivariateDistribution, lp::Real) = quantile(d, exp(lp))
```

But using quantile of course will lead to the original problem.

```
x = logaddexp(loglcdf, d.logtp - randexp(rng))
quantile(d0, exp(x))
```

I think I must have missed something there.

**Comment by devmotion** [comment]
> It seems it is just a wrapper of quantile method with exp(lp) after all:

That's just the generic fallback. For many distributions there exist optimized implementations of `invlogcdf`. E.g., for `Beta` we use `StatsFuns.betainvlogcdf`.

**Comment by devmotion** [comment]
> It seems the symmetric case works well to my surprise. i.e.

The reason for this observation is that it's problematic to add (or subtract) small numbers from 1 but not from 0.
```julia
julia> using Distributions

julia> d = truncated(Beta(100, 10); upper=0.5);

julia> d.lcdf
0.0

julia> d.tp
7.203401329871193e-21

julia> d.lcdf + d.tp == d.lcdf
false

julia> d = truncated(Beta(10, 100); lower=0.5);

julia> d.lcdf
1.0

julia> d.tp
7.203401329871193e-21

julia> d.lcdf + d.tp == d.lcdf
true
```
