### ISSUE TITLE
product_distribution deprecated?

### ISSUE THREAD

**Issue by oschulz** [JuliaStats/Distributions.jl#1589]
This is confusing:

```
julia> product_distribution(fill(Weibull(), 5))
┌ Warning: `product_distribution(dists::AbstractVector{<:UnivariateDistribution})` is deprecated, use `Product(dists)` instead.
```

But also

```
julia> Distributions.Product(fill(Weibull(), 5))
┌ Warning: `Product(v)` is deprecated, please use `product_distribution(v)`
```

**Comment by devmotion** [comment]
Ah I think I might have messed up this when I reverted `product_distribution(::AbstractVector{<:UnivariateDistribution})` to return a `Product` to avoid breaking changes.

Probably we should just remove both deprecations for now. `Product` will be removed but since users are not supposed to use `Product` directly they would get a deprecation warning even if they use `product_distribution`. And there's not really any future-proof alternative (I think) for users to `product_disttribution` as they are not supposed to call `ProductDistribution` either.

**Comment by oschulz** [comment]
>  And there's not really any future-proof alternative (I think) for users to product_disttribution

I agree, we need it to turn vectors of Normal to MvNormal and so on after all.

**Comment by devmotion** [comment]
Yes, exactly. These conversions are also not deprecated and won't be removed.
