### ISSUE TITLE
new versions available but cannot be upgraded because of other package

### ISSUE THREAD

**Issue by shuofanzhang** [JuliaStats/Distributions.jl#1616]
I am using a package GARCH v0.3.1, and it seems disturbing the package installation process, so my Distributions.jl is still v0.23.12.

Is there a way to get around it without giving up on using GARCH v0.3.1?

**Comment by devmotion** [comment]
I don't think we can do anything in Distributions about this unfortunately. One has to fix GARCH and update its Project.toml file. As you can see, since it did not specify upper bound for its dependencies at some point they were upper bounded automatically in the registry and hence it only supports up to Distributions 0.23: https://github.com/JuliaRegistries/General/blob/ae85bd68a65412602ab29733c890954e9944b744/G/GARCH/Compat.toml
