### ISSUE TITLE
Is the Success Probability for Distributions.NegativeBinomial Defined Correctly?

### ISSUE THREAD

**Issue by stephenstone** [JuliaStats/Distributions.jl#1634]
For the Negative Binomial Distribution in Distributions.jl the parameter p is defined as the success rate.  This is consistent with the formulas on Wikipedia.  However, it is being used as the failure rate in the formulas, which are consistent with the formulas on Wolfram.  Of course, the formulas can be written either way, but there is an inconsistency between the documentation and the implementation.  I have not provided any code because the issue is fairly straightforward.  If further clarification is needed, I can elaborate.

This issue has been raised before in a number of Issues, some of which are closed, but the documentation is still incorrect.  It should be an easy fix.

**Comment by devmotion** [comment]
I'm not sure if I understand you correctly, do you mean there's an error in the docstring (https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.NegativeBinomial)?

In the formula `p` is used as the success probability, as stated also in the text and the code snippet. `r` is the number of successes and fixed (corresponding to `n` in Mathematica), and the distribution then models the number of failures `k` (`x` in the documentation of Mathematica) before the `r`th success. To me it seems that's also what's stated in the formula, and both the docstring and Mathematica seem to be consistent. The only difference is the binomial coefficient but it is equivalent since `\binom{k + r - 1}{k} = \binom{k + r - 1}{(k + r - 1) - k)} = \binom{k + r - 1}{r - 1}`, corresponding to `\binom{n + x - 1}{n - 1}` in the notation in Mathematica.

**Comment by stephenstone** [comment]
Thank you for your quick and accurate response.  II did think there was an error in the docstring, but I was mistaken.
