### ISSUE TITLE
Uniform{Float32} pdf and cdf return inconsistent types

### ISSUE THREAD

**Issue by sethaxen** [JuliaStats/Distributions.jl#1677]
When passing a `Float64` to `pdf` or `logpdf`, for `Uniform{Float32}`, the result is a `Float32`, but for `cdf` and `logcdf`, the result is `Float64`: 

```julia
julia> using Distributions

julia> d = Uniform(0f0, 1f0)
Uniform{Float32}(a=0.0f0, b=1.0f0)

julia> pdf(d, 1.0)
1.0f0

julia> logpdf(d, 1.0)
-0.0f0

julia> cdf(d, 1.0)
1.0

julia> logcdf(d, 1.0)
0.0
```

**Comment by devmotion** [comment]
Hmm, I'm not sure if that is a bug or a feature. The simple explanation is that the computation of `pdf`/`logpdf` only requires branching on `x` to ensure that we return `0`/`-Inf` outside of the support but otherwise its value is not relevant - in contrast to `cdf`/`logcdf` where `x` directly enters the computations. Or put differently, we already know a priori that `pdf`/`logpdf` can only return two values where for `cdf`/`logcdf` its a whole interval of possible return values.

Regardless, I agree that it is a bit surprising.

**Comment by quildtide** [comment]
I think it might make sense to adopt the direction of `pdf(dist, x)` returning the type of `x`; same for `cdf`, `quantile`, etc.
