### ISSUE TITLE
`truncated` does not work with `Turing.jl`'s random variables

### ISSUE THREAD

**Issue by Tobias-Thomas** [JuliaStats/Distributions.jl#1889]
Hi,
I am currently building a [Turing.jl](https://github.com/TuringLang/Turing.jl) model and want to use the draw of one random variable as the bound for another one, using the `truncated` function.
While the usage does not throw an error, it definitely does not seem to work (see MWE below).
I already saw this other [issue](https://github.com/JuliaStats/Distributions.jl/issues/745), yet it was only about using random variables as parameters for the distribution. The case for using the draw of a random variable as a bound still seems to be not working.
Am I doing something wrong, or is there another way I could achieve using one random variable as the bound for another one?

```julia
a = 0:.05:1
b = 2 .- 1.5 * a + randn(21)
@model function truncate_mwe(x, y)
	intercept  ~ truncated(Normal(0, 1), 0, Inf)
	slope ~ truncated(Normal(0, 1), -intercept, Inf)

	for i in eachindex(y)
		y[i] ~ Normal(intercept + slope * x[i], 1)
	end
end
chain_mwe = sample(truncate_mwe(a,b), NUTS(), 1000)
```
For me, this chain always has some samples, for which intercept + slope < 0, which should not be the case as the maximum value for x in this case is 1.

Kind regards and thanks in advance for any help!

**Comment by devmotion** [comment]
Using `Inf` or `-Inf` as bounds for a truncated distribution leads to problems with ForwardDiff (the default automatic differentiation backend in Turing). Enabling NaN-safe mode (https://juliadiff.org/ForwardDiff.jl/dev/user/advanced/#Fixing-NaN/Inf-Issues) often fixes such issues. However, generally the better (and more efficient) approach is to construct the truncated distributions as `truncated(Normal(0, 1); lower=0)` and `truncated(Normal(0, 1); lower=-intercept))`. 

Unfortunately, AFAICT applying this fix is not sufficient for your model since Turing does not support random variables whose support changes dynamically (in this case the support of `slope` changes depending on the value of `intercept`): https://github.com/TuringLang/Turing.jl/issues/1558 https://github.com/TuringLang/Turing.jl/issues/1708 As described in the linked issues you can fix this by defining a custom distribution with a custom bijector.

**Comment by Tobias-Thomas** [comment]
> > Unfortunately, AFAICT applying this fix is not sufficient for your model since Turing does not support random variables whose support changes dynamically
> 
> I think @torfjelde fixed this recently.

Do you mean that only leaving out the `Inf` values is sufficient? If yes, I do not see this happening. I just adjusted the slope in the MWE to be -5 and again get lots of values where `intercept + slope < 0`.

**Comment by Tobias-Thomas** [comment]
> [TuringLang/Turing.jl#1558](https://github.com/TuringLang/Turing.jl/issues/1558) [TuringLang/Turing.jl#1708](https://github.com/TuringLang/Turing.jl/issues/1708) As described in the linked issues you can fix this by defining a custom distribution with a custom bijector.
Thank you for the explanation and the links! They look very promising and that definitely sounds like a solid workaround if it is not already natively supported.

**Comment by torfjelde** [comment]
> I think @torfjelde fixed this recently.

Yeah, this should be working now, as long as the `lower` and `upper` kwargs are used:)

**Comment by Tobias-Thomas** [comment]
> > I think @torfjelde fixed this recently.
> 
> Yeah, this should be working now, as long as the `lower` and `upper` kwargs are used:)

Ok, after updating my packages it works like a charm, thank you so much for the help and the implementation!!
