### ISSUE TITLE
linear transformations on MvNormal

### ISSUE THREAD

**Issue by goretkin** [JuliaStats/Distributions.jl#307]
Are these functions within the scope of the package? These seem harmless

```
+(x::AbstractVector,n::MvNormal) = MvNormal(n.μ+x,n.Σ)
+(n::MvNormal,x::AbstractVector) = MvNormal(n.μ+x,n.Σ)
Xt_A_X
*(A::AbstractMatrix,n::MvNormal) = MvNormal(A*n.μ,  PDMats.Xt_A_X(n.Σ,A)  )
```

More contentious is allowing `+(x::MvNormal,y::MvNormal)`, assuming independence.

My main motivation was from seeing the [StateSpace](https://github.com/ElOceanografo/StateSpace.jl) package that @ElOceanografo wrote. For example: https://github.com/ElOceanografo/StateSpace.jl/blob/master/src/KalmanFilter.jl#L49 . Having functions for linear transformations of Multivariate Normal distributions might improve readability in only a minor way, but they might be worth including in Distributions anyway.

**Comment by mschauer** [comment]
I am running into the same problem trying to port a Kalman filter now from 
https://github.com/mschauer/GaussianDistributions.jl/blob/master/src/GaussianDistributions.jl
to Distributions. How do you see this?

**Comment by simonbyrne** [comment]
It would be good to have some way to do this, at least for constants. Mathematically, I'm a bit reluctant to overload `+`/`*` directly: the objects are intended to be distributions, not random variables. But maybe that isn't such a big deal?

Alternatively we could overload `map` (e.g. so that you would do `map(x -> x + k, d)`), but that would require much more "plumbing" to get it to work.

**Comment by goretkin** [comment]
I hadn't considered making the distinction between an object that
represents a distribution and an object that represents a random variable
following that distribution, but I agree that the distinction certainly can
exist. Can we think of a case where this distinction serves a purpose?

**Comment by simonbyrne** [comment]
I mean, the only other interpretation it could mean would be transforming it as a measure, but (a) that isn't very useful (since it would no longer be a probability measure), and (b) we don't treat it as a measure in other contexts, e.g. defining `(d::Distribution)(x::Interval)` to get the probability of an interval.

> independent sum deserves a new symbol like ⊕

That's a great idea!

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
