### ISSUE TITLE
MixtureModel with Continuous and Discrete

### ISSUE THREAD

**Issue by dfagnan** [JuliaStats/Distributions.jl#332]
Is there a reason not to allow for mixtures with both continuous and discrete underlying distributions?

It seems like right now it would break the model, since it would be neither discrete nor continuous in terms of ValueSupport. I guess this would be a major change.

```
MixtureModel([Normal(); Geometric(0.5)])

ERROR: `variate_form` has no method matching variate_form(::Type{Sampleable{F<:V
ariateForm,S<:ValueSupport}})
 in MixtureModel at C:\Users\David\.julia\v0.3\Distributions\src\mixturemodel.jl
:20
 in MixtureModel at C:\Users\David\.julia\v0.3\Distributions\src\mixturemodel.jl
:29
```

**Comment by lindahua** [comment]
Yes, all components should be on the same space. We haven't explicitly enforced this constraint yet, but need to work on this.

**Comment by abraunst** [comment]
What about atomic distributions, are they continuous or discrete? More in particular, how does a distribution which is a mixture of continuous and point-mass fits here? Is it continuous or discrete? (math answer IMO: it is neither -- continuous and discrete are not complementary)

Real example:  I'm interested in spike-and-slab or Gauss-Bernoulli (mixture of an atomic point-mass distribution and a normal). Right now it seems the only way of producing this is by using a degenerate normal with sigma=0 instead of a point-mass. Is this intended?

**Comment by matbesancon** [comment]
@abraunst I think in that case you should construct your own mixture type in that case, not use the common one, assuming same space for the two distributions seems expectable

**Comment by abraunst** [comment]
While I agree with your statement, I think that "continuous" is a bit ambiguous: it may mean that the distribution is defined on the real line (i.e. a distinction on the space on which is defined, as you mention) or that it is absolutely continuous. I think that the former is more useful.

So, in my humble opinion, discrete should mean that the distribution is defined on a subset of Z or Z^n (and continuous all other cases). In this interpretation the point mass (and mixtures of point mass) should be continuous.

**Comment by mschauer** [comment]
The absolute continuity is best seen as a property of the `pdf`. Continuous then just means that the pdf is given with respect to the Lebesgue measure.
