### ISSUE TITLE
Random Numbers differs in Julia v0.3 and v0.4 nightly?

### ISSUE THREAD

**Issue by vgupta1** [JuliaStats/Distributions.jl#338]
Hi all, 

I've noticed that the following code generates different values in Julia v0.3 (Version 0.3.0 (2014-08-20 20:43 UTC)) and v0.4 (nightly build off release page):
``` julia
using Distributions
srand(8675309)
dist = DiscreteUniform(100)
println(rand(dist, 10))
```
Is this by design?  Is it perhaps related to (JuliaLang/julia#8874)?  Is there a way to recover the old behavior?  I ask because all of my tests are now broken.

@IainNZ

**Comment by johnmyleswhite** [comment]
Yeah, we intentionally decoupled the RNG's for Distributions. I think we still don't quite know what our ultimate goal is, but I know that we wanted to remove all uses of Rmath for RNG's, which means that exact results should generally change.

**Comment by vgupta1** [comment]
Is there a current best practice suggestion for testing then?

**Comment by johnmyleswhite** [comment]
Testing with the RNG's is really hard. There are some people hardcoding values, but I tend to implement theoretical CI's based on sample size and confirm that empirical values live inside those CI's.

**Comment by andreasnoack** [comment]
Do we have a julia function defined for setting the Rmath RNG?

2015-01-22 17:25 GMT-05:00 John Myles White <notifications@github.com>:

**Comment by johnmyleswhite** [comment]
@simonbyrne is probably the one who knows the answer to that.

**Comment by simonbyrne** [comment]
`srand` should still set the seed of the RNG, it's just that how the RNGs are set up has changed, see #8832. From what I understand, there are now two different RNGs operating: the "new" one for the Julia-basd functions (such as this one, which is why the numbers are different), and the "old" one for the Rmath-based methods.

In general, it's probably not feasible to get the same streams between versions, at least until the remaining RNG issues have been settled.
