### ISSUE TITLE
fit_mle has no AbstractArray methods

### ISSUE THREAD

**Issue by durcan** [JuliaStats/Distributions.jl#360]
I am not sure if there is some subtle reason for this but the fitting methods in Distributions seem to only take sample sets of type Array (e.g. [Normal fitting](https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/normal.jl#L184-218)). This means that anyone working with ArrayView or DataArray types will have to do a lot of explicit conversions and create a bunch of temporary arrays before calling fit_mle. Is there a reason that these sort of methods could not work with an AbstractArray?

**Comment by johnmyleswhite** [comment]
Many of the methods could be safely relaxed to AbstractArray, although the methods could not be safely used with DataArrays. (They would work correctly with `NullableArray{Float64}` because those are clearly not a form of `AbstractArray{Float64}`.)

If you're up for it, the best thing to do would be to go through the codebase and determine where the real active constraint is that input needs to be an iterable with Float64 values. Then we can use NULL-dropping iterators to make things work with `NullableArray{Float64}`.

**Comment by lindahua** [comment]
fixed by aa816dd
