### ISSUE TITLE
Standardize parameter requirements

### ISSUE THREAD

**Issue by bdeonovic** [JuliaStats/Distributions.jl#406]
Some distributions have constrained parameters (e.g. Binomial `p` is constrained to be `[0,1]` or poisson has lambda `(0,infty)`). For some of these the parameters are allowed to be on the boundary (e.g. Binomial, `p` can be 0 or 1), but for others they are not allowed be to be on boundary (e.g. geometric `p` is strictly 0 < p < 1 or poisson lambda has to be strictly greater than 0)

I would like these to be standardized. In particular I would like to always allow boundary values.

**Comment by johnmyleswhite** [comment]
I'd be much more in favor of doing what's in standard textbooks. I'm still pretty uncomfortable with the Poisson zero-mean distribution.

**Comment by bdeonovic** [comment]
Is that what is currently done? If so what is the textbook? I just found it a big confusing that for the binomial p could be [0,1] but for geometric its (0,1).

**Comment by johnmyleswhite** [comment]
When I was doing work on this library, I was generally working from http://www.amazon.com/Statistical-Distributions-Catherine-Forbes/dp/0470390638 but we should really standardize on a single source of truth.

My impression is that the book series containing "Continuous Univariate Distributions, Vol. 1" is really the canonical listing for all distributional information.

I'm happy to adopt any convention that ensures consistency, although it's clear we need to occasionally bend some rules. I imagine the argument for the geometric distribution is that the resulting distributions are totally degenerate and violate assumptions about the support, whereas the binomial case doesn't violate support invariants.

**Comment by andreasnoack** [comment]
Even though I think we should use authoritative sources as much as possible I also think that the goal in text books and encyclopedias is a little different from our goal. Usually, books aim to classify the different distributions by their respective characteristics and because distributions are often degenerate on the boundary of the parameter space it is clearner to exclude them in the exposition. However, that might not be the most convenient thing from a computation/practical viewpoint.

In the world of calculus you are also free to go arbitrarily close to the boundary, but that is not possible on a computer so rounding might force you to a value on the boundary.

My vote is for allowing values at the boundary whenever it makes sense. The question, of course, what "makes sense" means, but it seems reasonable that the limit is at least a probability distribution. One problem is continuous distributions which are degenerate on the boundary such that the `pdf` becomes discontinuous in numerical value as well as underlying measure.

With the above criterion, it would be okay with `Geometric(1.0)`, but not `Geometric(0.0)` and I think we could tell a consitent story, but there is probably other distributions where things are complicated.

**Comment by johnmyleswhite** [comment]
Yeah, that does seem right to me. I'd be alright with allowing boundary values of parameters subject to the constraint that the resulting probability distribution is a point mass. If that constraint proves too strict, we could consider relaxing it in some sensible way in the future as more cases come up. But for now that restriction would give us a consistent justification for allowing all of `Poisson(0.0)`, `Bernoulli(0.0)`, `Bernoulli(1.0)`, `Geometric(1.0)`, but not `Geometric(0.0)`. It would also allow `Normal(0.0, 0.0)`.

**Comment by andreasnoack** [comment]
If we allow `Normal(μ,0)`, I think we should either throw for `pdf(Normal(μ,0))` or return the pointwise limit of the pdf, i.e. `Inf`. It seems very wrong the return the pmf value 1.

We would have to come up with a general rule for the continuous distributions, but that can probably be done completely independent from the discrete distributions just discussed.

**Comment by johnmyleswhite** [comment]
That sounds like we should separate the rule by whether it collapses to a PMF at a single point vs a Dirac delta. It seems the core question is whether the distribution object should be constructible at all: after that, we can decide what methods are still applicable.

**Comment by lindahua** [comment]
Generally, I think it doesn't hurt to allow these boundary cases as long as the behaviors/semantics are clearly defined.

This issue can be separated into multiple questions:

(1) Should we allow degenerated distributions to be *constructed*? (My vote is *yes*)

(2) Should we allow `pdf` etc to be evaluated for degenerated distributions? (My vote is *yes*, and this function may yield `Inf` or `0`). That being said, I am also ok with *no*, in which case, an exception will be raised whenever we call `pdf` or `logpdf` over such distributions.

**Comment by matbesancon** [comment]
discussion here doesn't seem to be an issue, closing
