### ISSUE TITLE
How can I evaluate the probability (i.e., CDF) when we use the array as an input?

### ISSUE THREAD

**Issue by MSYoon** [JuliaStats/Distributions.jl#514]
I have been trying to evaluate the CDF with array inputs. 

For example, I have different sets of means, sigmas, and x (to be evaluated) as shown below.

means=[0  0.5 1];
sigmas=[0.25 0.5 0.25];
x=[4, 5, 6];

prob=cdf( Normal (means, sigmas), x);

However, this "Normal" function seems not to support the array inputs to evaluate the CDF probability. 

Note that I want to avoid "for loop" to reduce the computational load because I use a huge size of matrices in reality. 

Please advise me how to deal with this problem.

**Comment by KristofferC** [comment]
What do you mean to "reduce computational load" by avoiding a for loop?

**Comment by ararslan** [comment]
Note that in R there's a lot of stigma against `for` loops because they carry a lot of extra garbage around at each iteration, so people recommend vectorized operations instead. Julia is quite the opposite; loops are very efficient.

Julia also has `map` and `broadcast` for operations over arrays, both of which are similarly efficient. In this case you could simply use `map`:
```julia
map((μ, σ, q) -> cdf(Normal(μ, σ), q), means, sigmas, x)
```
This is applys a three-argument function that acts on the elements of the arrays over the three arrays simultaneously.

I don't know how large your vectors are, but here's a benchmark on my computer using Julia 0.5 with a million elements per array.
```julia
julia> means = randn(1_000_000); sigmas = rand(1_000_000); x = rand(1_000_000);

julia> @time prob = map((μ, σ, q) -> cdf(Normal(μ, σ), q), means, sigmas, x);
  0.179899 seconds (28.31 k allocations: 8.778 MB, 45.93% gc time)
```

**Comment by andreasnoack** [comment]
...or the comprehension version

[cdf(Normal(μ,σ), q) for (μ,σ,q) in zip(means,sigmas,x)];

**Comment by simonster** [comment]
Since this is a normal distribution you could also just subtract the mean and divide by sigma. Then you can just use the standard normal CDF.

**Comment by MSYoon** [comment]
Those are very helpful. Thank you all!
