### ISSUE TITLE
Simulation for the Normal Inverse Gaussian distribution

### ISSUE THREAD

**Issue by robertdj** [JuliaStats/Distributions.jl#524]
I've implemented a simulation algorithm for the NIG distribution. I'd be happy to share, but I'm unsure how. 
I usually add commits to the master branch, push to my local fork and make a PR, but the master branch seems to be way behind the v0.10.2 tag on my local machine. 
What would you prefer?

**Comment by jmxpearson** [comment]
I think you have a couple of options (if I understand correctly):

1. From your fork:
  1. pull changes from upstream to your local master branch
  1. push to your fork
  1. rebase your feature branch against the updated master

1. If you follow the steps [here](http://docs.julialang.org/en/release-0.4/manual/packages/#code-changes) you should be able to submit a PR from within the REPL. You don't need to have a fork for that. It will help, though, if your local copy is reasonably up-to-date, since there have been recent changes to NIG.

**Comment by robertdj** [comment]
I ran `Pkg.update()` just before my first message; it's at `v0.10.2`. 
What surprised is that when I ran `git checkout master` at the shell, `master` was far behind the current version. 
I'll try the steps you listed.

**Comment by jmxpearson** [comment]
There have been a couple of PRs go through. I don't think they're likely to interfere with NIG, though.

**Comment by robertdj** [comment]
My [pull request](https://github.com/JuliaStats/Distributions.jl/pull/526) decreases the code coverage and fails the test. 
I don't know how to test a simulation algorithm. Looking at other test scripts in the package it seems that tests involving `rand` test stuff like the size and type of the array holding the simulation results. 
Is that sufficient?
