### ISSUE TITLE
eltype for multivariate distributions

### ISSUE THREAD

**Issue by zsunberg** [JuliaStats/Distributions.jl#596]
When I initially started using Distributions.jl, I assumed that the `eltype(d)` was meant to return the type that would be returned by `rand(d)`. This is true for univariate distributions, but for multivariate, it is not, e.g.
```julia
eltype(MvNormal(eye(2)))
```
returns `Float64` when I would expect it to return `Array{Float64, 1}`.

I have two questions regarding this:
1. Does anyone remember the reasoning behind this decision?
2. Is there another mechanism that I'm missing that would allow me to infer the type that will be returned by `rand`?

**Comment by ararslan** [comment]
In general, `eltype` returns the element type. So `eltype` on a Distribution should be the same as the _element type_ of the output of `rand`, not the _type_ of the `rand` output. This is the basic interface one can assume for `eltype` for any implementation, in Base or in packages.

Since you know that the output of `rand` with have `eltype` equal to the distribution's `eltype` and you know the dimensions you requested from `rand`, you already know the return type: `Array{T,N}`, where `T` is the `eltype` and `N` is the number of requested dimensions.

**Comment by zsunberg** [comment]
Ok, got it, thanks @ararslan - that makes sense with `length` as well. That solves the issue, but I'd like to ask one more question to make the julia ecosystem better:

For one of our projects (POMDPs.jl), we would like to define distributions over objects of any type, e.g. things that are not numbers or vectors. I want to define a function that returns the type that will be returned by `rand`. Does anyone have suggestions for the name of this function?

`outcome_type`?
`domain_eltype`?

**Comment by ararslan** [comment]
Maybe `sampletype` or something like that, since `rand` is in effect drawing a sample from the given distribution.

Anyway, closing this since the primary issue has been resolved.
