### ISSUE TITLE
Would the Polya-Gamma distribution make sense for this package?

### ISSUE THREAD

**Issue by currymj** [JuliaStats/Distributions.jl#685]
It's a very useful distribution in Bayesian statistics, for various reasons. It can be sampled from efficiently and all of its moments can be evaluated in closed form. So that gives a lot of functions that the documentation suggests are required.

It doesn't have a closed-form density, though (it has a nice analytic formula which unfortunately involves an infinite sum).

Would it still fit into this package? If not, I'll likely still implement it, certainly at least as a `Sampleable{Univariate, Continuous}`. But would it make sense to make it a full `UnivariateDistribution`, even if I wouldn't be able to provide `pdf`, `logpdf`, `quantile`, etc.? Or would everything just break immediately?

**Comment by kmsquire** [comment]
I'll offer an opinion, but I'm hoping others will chime in. 

I think the answer is probably "no", it doesn't belong here.  For a prior reference, a long, long time ago, conjugate distributions were split out into their own [ConjugatePriors.jl package ](https://github.com/JuliaStats/ConjugatePriors.jl).  Arguably, these are distributions in their own right (and I believe they all define `pdf`, etc.), but in reality, they're only used in Bayesian statistics, and my impression is that the distributions defined here are mostly common, parameterized distributions that one would learn about in a statistics class (and which define `pdf`, etc.).

That said, it sounds like it would be great to have such a distribution available somewhere, probably in its own package.  Pinging relevant parties who work with MCMC samplers in Julia, and who might be interested and have relevant opinions.

* @brian-j-smith (https://github.com/brian-j-smith/Mamba.jl)
* @scidom (https://github.com/JuliaStats/Klara.jl)
* @yebai (https://github.com/yebai/Turing.jl)

Others should feel free to comment or contradict me, since I don't do a lot with this package right now.

**Comment by jmxpearson** [comment]
I think it would be very useful to have it implemented *somewhere*, but part of the baseline expectation for Distributions, I think, is that most (ideally all) parts of the interface are implemented. 

I am one of those people who would appreciate the effort. Possibly also @jdrugo.

**Comment by currymj** [comment]
Given that it's in a separate package, would it still make sense to subtype `UnivariateDistribution` even if functions related to the density are not implemented? Or would that be unwise/result in lots of errors as other code assumes they exist?

Are there distributions in other packages that you know of with the `pdf`, `logpdf`, etc functions missing? (Even an unnormalized density doesn't exist here.)

**Comment by kmsquire** [comment]
It seems to me that one of the reasons to subtype `UnivariateDistribution` is that it can use much of the machinery documented [here](https://juliastats.github.io/Distributions.jl/latest/univariate.html) and defined [here](https://github.com/JuliaStats/Distributions.jl/blob/2d98eb6f31e9a92cce416e7391a84cff9bba7292/src/univariates.jl), and that the user can assume that useful parts of that machinery work.  From your first post, it sounds like that might be the case?

I would say that it's probably okay if some functions didn't work--e.g., the Cauchy distribution doesn't have a defined mean or variance (or any other higher order moment), but it's still a `UnivariateDistribution`.  As long as users understand this, that's fine.

I have no idea if any packages that could use this (e.g., in any of the MCMC samplers I mentioned above) require the `pdf`, etc., to exist, so I would suggest looking at them to see.

Or, you can just define it as a `UnivariateDistribution` and see what breaks. ;-)

**Comment by jmxpearson** [comment]
I think it makes a lot of sense to subtype. I would think you would want to be able to pass an instance wherever a `UnivariateDistribution` would be appropriate and the relevant method makes sense.

Besides, users of your package should be knowledgeable enough to understand what is and isn't a valid method to use (and you can document that).

**Comment by currymj** [comment]
I'm going to close this issue, as my question has been very helpfully answered! Thanks!

I've begun work on [PolyaGammaDistribution.jl](https://github.com/currymj/PolyaGammaDistribution.jl). Right now it's a pretty literal translation of the R code from BayesLogit (the package that goes along with the original Pólya-Gamma augmentation paper).

I have some rudimentary test cases and `mean`, `var`, and `rand` implemented and it seems to work, or anyway the summary statistics seem reasonably close to what comes out of the R package. If you're interested, check it out! Any contributions or suggestions would be appreciated. It is definitely slow, awful code right now, but that will change.
