### ISSUE TITLE
Type instability in pdf(::MixtureModel, x)

### ISSUE THREAD

**Issue by axsk** [JuliaStats/Distributions.jl#686]
As of current type inference does not work for MixtureModels:
``` julia
d=MixtureModel([Normal()])
@code_warntype pdf(d,rand(d))
```
resulting in
```
[...]
end::Any
```

**Comment by andreasnoack** [comment]
The problem is that [this field](https://github.com/JuliaStats/Distributions.jl/blob/3789c4f320eba3cddc299463d5e370c1de8ae4d2/src/mixtures/mixturemodel.jl#L18) is no longer concrete because `Categorical` is now parametric on the type of the parameters. I think the solutions is to add a fourth (sigh) parameter to `MixtureModel`. It would be great if you could prepare a PR.
