### ISSUE TITLE
fit_mle not working for arguments Gamma and Array with missing data

### ISSUE THREAD

**Issue by GdMacmillan** [JuliaStats/Distributions.jl#786]
I have a DataFrame with some missing data. 
`file = "data/rainfall.csv"
df = CSV.File(file) |> DataFrame;`
This works:
`plot(histogram(df.Jan, normalize = true, bins=20))`
I want to fit a Gamma distribution to a column that has missing values.
`fit_mle(Gamma, df.Jan)`

```
suffstats is not implemented for (Gamma, Array{Union{Missing, Float64},1}).

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] suffstats(::Type{Gamma}, ::Array{Union{Missing, Float64},1}) at <home>/.julia/packages/Distributions/WHjOk/src/genericfit.jl:5
 [3] fit_mle(::Type{Gamma}, ::Array{Union{Missing, Float64},1}) at <home>/.julia/packages/Distributions/WHjOk/src/genericfit.jl:27
 [4] top-level scope at In[59]:1
```
When I use a subset of the data
```
data = [6.15;6.41;4.05;3.34;6.32]
-element Array{Float64,1}:
 6.15
 6.41
 4.05
 3.34
 6.32
```
The fit method works
```
gd = fit_mle(Gamma, data)
Gamma{Float64}(α=14.680176290746886, θ=0.3578976093980334)
```

What are some strategies for handling this? I have used the pdf function on a gamma distribution with the full dataset and have not encountered the same problem. This is my first issue here so go easy on me. I'm learning julia.

**Comment by matbesancon** [comment]
@GdMacmillan very sorry for the delays you experienced. When you need help using thigns, the best solution is often [Discourse](http://discourse.julialang.org/) or Slack, check julialang.org/community for more info.

Indeed distributions does not have a ready-to-go solution for missing data because this is an open-problem. Simply taking the present data to compute statistics would be dangerous, as it can create a bias

**Comment by matbesancon** [comment]
Closing it for now, sorry again
