### ISSUE TITLE
RFC: Remove PDMats dependency?

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaStats/Distributions.jl#940]

**Comment by ararslan** [comment]
Can you elaborate on why this would be beneficial?

**Comment by matbesancon** [comment]
this has been discussed in other issues, having PDMats.jl brings in very heavy dependencies, it would be better to use `AbstractPDMat` which would ideally live in a package separated from the `PDMat` implementation

**Comment by matbesancon** [comment]
https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl
Maybe?
cc @andreasnoack

**Comment by jasonsun0310** [comment]
I agree that it's better without PDMat since ARPACK is not well supported on Julia built with Intel MKL library. Plus there are some other well written ARPACK alternatives that performs just as well, e.g. KrylovKit.jl and IterativeSolvers.jl.

**Comment by vilim** [comment]
Could this please be considered again? Distributions is the only package I commonly use and that fails with MKL 
I noticed there is also [ArpacMKL]( https://github.com/JuliaLinearAlgebra/ArpackMKL.jl), but I don't know how to link it to PDMat

**Comment by iamed2** [comment]
PDMats no longer requires Arpack

**Comment by matbesancon** [comment]
@nickrobinson251 closing this, feel free to chime in if there are still motivation for that

**Comment by johnczito** [comment]
I encountered another motivation for this. The Turing folks have a package [`DistributionsAD.jl`](https://github.com/TuringLang/DistributionsAD.jl) which, among other things, includes line-for-line recodings of the `MvNormal`, `Dirichlet`, `Wishart`, `InverseWishart`, and more. One of the reasons they find this necessary is because `PDMats` apparently doesn't play nice with the AD stuff they're trying to do (see [here](https://github.com/TuringLang/DistributionsAD.jl/pull/84#issuecomment-640215092), and surrounding chat).

It would definitely be better if they could just build on top of what's provided here.

**Comment by ararslan** [comment]
From that issue:

> PDMats also causes issues when trying to differentiate wrt the random variable for almost all AD backends

Seems like that's something that should be addressed in PDMats rather than just removing PDMats from other packages. If it breaks AD systems because of the Cholesky decomposition, that's differentiable (and is implemented in [Nabla](https://github.com/invenia/Nabla.jl) and [ChainRules](https://github.com/JuliaDiff/ChainRules.jl)) so it should be fixable. Otherwise it would be good if AD folks could open issues on PDMats.

**Comment by johnczito** [comment]
> Seems like that's something that should be addressed in PDMats rather than just removing PDMats from other packages.

Good point. And using ChainRules to fix this has [come up](https://github.com/TuringLang/DistributionsAD.jl/issues/65#issuecomment-620752798).
